// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ldmvnrm_list_arma_fast
arma::mat ldmvnrm_list_arma_fast(arma::mat const& x, arma::colvec const& mean, arma::mat const& sigma_list);
RcppExport SEXP _minorbsem_ldmvnrm_list_arma_fast(SEXP xSEXP, SEXP meanSEXP, SEXP sigma_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::colvec const& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type sigma_list(sigma_listSEXP);
    rcpp_result_gen = Rcpp::wrap(ldmvnrm_list_arma_fast(x, mean, sigma_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_minorbsem_ldmvnrm_list_arma_fast", (DL_FUNC) &_minorbsem_ldmvnrm_list_arma_fast, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_minorbsem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
