# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldmvnrm_list_arma_fast <- function(x, mean, sigma_list) {
    .Call(`_minorbsem_ldmvnrm_list_arma_fast`, x, mean, sigma_list)
}

